version: "3"

services:
  client:
    build: client
    ports:
      - 3002:5000
    depends_on:
      - api
  api:
    build: api
    ports:
      - 3001:8080
    depends_on:
      - redis
  redis:
    image: redis
